# nginx proxy address - http://172.17.0.1:9411

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  answer:
    image: answer/answer:latest
    container_name: answer-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - answer
    ports:
      - "9411:9411"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/answer:/config
      - ./rootfs/data/answer:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9411"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  answer:
    external: false
